[project]
name = "carsalesman"
version = "0.1.0"
description = "Salesman chatbot for Car dealer companies"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=6.0.2",
    "numpy==1.26.4",
    "pandas==2.2.0",
]
